# URL for git clone
GIT_URL=https://github.com/named-data/NLSR

# Tag name or commit hash for checkout
GIT_VERSION=02e32996c7576f7476ddda2d87965b4dfbbbddc7

# Package name
NAME=nlsr

# Package version
VERSION=0.2.0~rc0.2-0.1.0-46-g02e3299

# PPA version
PPA_VERSION=1

include ../packaging.mk
