# URL for git clone
GIT_URL=https://github.com/named-data/NLSR

# Tag name or commit hash for checkout
GIT_VERSION=cae33b69f2544d467273b5c05ee25266d7c31e09

# Package name
NAME=nlsr

# Package version
VERSION=0.2.0-5-gcae33b6

# PPA version
PPA_VERSION=1

include ../packaging.mk
