# URL for git clone
GIT_URL=https://github.com/named-data/NLSR

# Tag name or commit hash for checkout
GIT_VERSION=2b057af9e1a695bb72a662b22cc1e8be200356f3

# Package name
NAME=nlsr

# Package version
VERSION=0.3.0-13-g2b057af

# PPA version
PPA_VERSION=1

include ../packaging.mk
