# URL for git clone
GIT_URL=https://github.com/named-data/NFD.git

# Tag name or commit hash for checkout
GIT_VERSION=NFD-0.3.1

# Package name
NAME=nfd

# Package version
VERSION=0.3.1

# PPA version
PPA_VERSION=3

include ../packaging.mk
