# URL for git clone
GIT_URL=https://github.com/named-data/NFD.git

# Tag name or commit hash for checkout
GIT_VERSION=bb964663a97f3fbfb70dc78789cf592f9454ab98

# Package name
NAME=nfd

# Package version
VERSION=0.2.0~rc0.1

# PPA version
PPA_VERSION=1

include ../packaging.mk
