# URL for git clone
GIT_URL=https://github.com/named-data/NFD.git

# Tag name or commit hash for checkout
GIT_VERSION=a3295741d6c21b95146145000e7b002cb1e7e062

# Package name
NAME=nfd

# Package version
VERSION=0.2.0~rc0

# PPA version
PPA_VERSION=1

include ../packaging.mk
