# URL for git clone
GIT_URL=https://github.com/named-data/ndns

# Tag name or commit hash for checkout
GIT_VERSION=28229df052fe40f00e1e4e9798b44be1e17a4ddc

# Package name
NAME=ndns

# Package version
VERSION=0.0.12-g28229df

# PPA version
PPA_VERSION=1

include ../packaging.mk
