# URL for git clone
GIT_URL=https://github.com/named-data/ndns

# Tag name or commit hash for checkout
GIT_VERSION=d6b3bda24b001e9bc909188c25f45a084b8c3046

# Package name
NAME=ndns

# Package version
VERSION=0.0.1

# PPA version
PPA_VERSION=2

include ../packaging.mk
