# URL for git clone
GIT_URL=https://github.com/named-data/ndns

# Tag name or commit hash for checkout
GIT_VERSION=d091e31269bd0c8042e89b775b94804651878cad

# Package name
NAME=ndns

# Package version
VERSION=0.0.9-gd091e3

# PPA version
PPA_VERSION=1

include ../packaging.mk
