# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tlv-ping

# Tag name or commit hash for checkout
GIT_VERSION=ndn-tlv-ping-0.1.0

# Package name
NAME=ndn-tlv-ping

# Package version
VERSION=0.1.0

# PPA version
PPA_VERSION=2

include ../packaging.mk
