# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tlv-ping

# Tag name or commit hash for checkout
GIT_VERSION=3970fdbfc83cb580af75bd8219fefdbfee6c21d9

# Package name
NAME=ndn-tlv-ping

# Package version
VERSION=0.0.0

# PPA version
PPA_VERSION=1

include ../packaging.mk
