# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tlv-ping

# Tag name or commit hash for checkout
GIT_VERSION=1283684bacb2352de38c8f0ad21a069875583d91

# Package name
NAME=ndn-tlv-ping

# Package version
VERSION=0.1.4

# PPA version
PPA_VERSION=3

include ../packaging.mk
