# URL for git clone
GIT_URL=https://github.com/named-data/name-based-access-control.git

# Tag name or commit hash for checkout
GIT_VERSION=dddc19aef4cb67df70f74395aa3e38c2a49c4f79

# Package name
NAME=name-based-access-control

# Package version
VERSION=0.1.1-commit-dddc19a

# PPA version
PPA_VERSION=1

include ../packaging.mk
