# URL for git clone
GIT_URL=https://github.com/named-data/name-based-access-control.git

# Tag name or commit hash for checkout
GIT_VERSION=61a8003

# Package name
NAME=name-based-access-control

# Package version
VERSION=0.1.0-commit-61a8003

# PPA version
PPA_VERSION=0

include ../packaging.mk
