# URL for git clone
GIT_URL=https://github.com/named-data/name-based-access-control.git

# Tag name or commit hash for checkout
GIT_VERSION=a7ac15b778009ea6eaa174032e5cc69385db566b

# Package name
NAME=name-based-access-control

# Package version
VERSION=0.1.2-commit-a7ac15b77

# PPA version
PPA_VERSION=1

include ../packaging.mk
