# URL for git clone
GIT_URL=https://github.com/named-data/PSync.git

# Tag name or commit hash for checkout
GIT_VERSION=0.1.0

# Package name
NAME=libpsync

# Package version
VERSION=0.1.0

# PPA version
PPA_VERSION=1

include ../packaging.mk
