# URL for git clone
GIT_URL=https://github.com/named-data/PSync.git

# Tag name or commit hash for checkout
GIT_VERSION=17b266c3a0313d9bf1266f69337da6a3acff983e

# Package name
NAME=libpsync

# Package version
VERSION=0.1.0-6-g17b266c

# PPA version
PPA_VERSION=1

include ../packaging.mk
