# URL for git clone
GIT_URL=https://github.com/named-data/PSync.git

# Tag name or commit hash for checkout
GIT_VERSION=32ccfc4d1d4db648763bf96ffdf8ac87f0bc3f50

# Package name
NAME=libpsync

# Package version
VERSION=0.3.0-9-g32ccfc4

# PPA version
PPA_VERSION=1

include ../packaging.mk
