# URL for git clone
GIT_URL=https://github.com/named-data/ndn-traffic-generator

# Tag name or commit hash for checkout
GIT_VERSION=06784b41cc38cb75f7f980dcca003daa9ec9832d

# Package name
NAME=ndn-traffic-generator

# Package version
VERSION=0.0.16-g06784b41

# PPA version
PPA_VERSION=1

include ../packaging.mk
