# URL for git clone
GIT_URL=https://github.com/named-data/ndn-traffic-generator

# Tag name or commit hash for checkout
GIT_VERSION=51459409bdc2c70fe7804eb6df7a0917cb0c1259

# Package name
NAME=ndn-traffic-generator

# Package version
VERSION=0.0.10-g51459

# PPA version
PPA_VERSION=1

include ../packaging.mk
