# URL for git clone
GIT_URL=https://github.com/named-data/ndn-traffic-generator

# Tag name or commit hash for checkout
GIT_VERSION=6f33e0ffca38158700413eba663f558960abc2df

# Package name
NAME=ndn-traffic-generator

# Package version
VERSION=0.0.6-g6f33e

# PPA version
PPA_VERSION=4

include ../packaging.mk
