# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tools

# Tag name or commit hash for checkout
GIT_VERSION=ndn-tools-0.2

# Package name
NAME=ndn-tools

# Package version
VERSION=0.2

# PPA version
PPA_VERSION=6

include ../packaging.mk
