# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tools

# Tag name or commit hash for checkout
GIT_VERSION=d2300731edd88593290ac0c33ed25d5b353b6634

# Package name
NAME=ndn-tools

# Package version
VERSION=0.3-6-gd230073

# PPA version
PPA_VERSION=1

include ../packaging.mk
