# URL for git clone
GIT_URL=https://github.com/named-data/ndn-tools

# Tag name or commit hash for checkout
GIT_VERSION=cc2c717b6289019acc45f209fce5e4cd10c31e72

# Package name
NAME=ndn-tools

# Package version
VERSION=0.5-14-gcc2c717b

# PPA version
PPA_VERSION=3

include ../packaging.mk
