# URL for git clone
GIT_URL=https://github.com/named-data/ndn-cxx.git

# Tag name or commit hash for checkout
GIT_VERSION=895395f7f666445712171bb7b7e82387682b3c84

# Package name
NAME=ndn-cxx

# Package version
VERSION=0.3.1-3-g895395f

# PPA version
PPA_VERSION=1

include ../packaging.mk
