# URL for git clone
GIT_URL=https://github.com/named-data/ndn-cxx.git

# Tag name or commit hash for checkout
GIT_VERSION=ndn-cxx-0.5.1

# Package name
NAME=ndn-cxx

# Package version
VERSION=0.5.1

# PPA version
PPA_VERSION=4

include ../packaging.mk
