# URL for git clone
GIT_URL=https://github.com/named-data/ndn-cxx.git

# Tag name or commit hash for checkout
GIT_VERSION=ndn-cxx-0.6.3

# Package name
NAME=ndn-cxx

# Package version
VERSION=0.6.3

# PPA version
PPA_VERSION=3

include ../packaging.mk
