# URL for git clone
GIT_URL=https://github.com/named-data/ndndump

# Tag name or commit hash for checkout
GIT_VERSION=0ce60362a285f42cf2ecbeea8cff0c7919d28d72

# Package name
NAME=ndndump

# Package version
VERSION=0.5.3

# PPA version
PPA_VERSION=7

include ../packaging.mk
