# URL for git clone
GIT_URL=https://github.com/named-data/ndndump

# Tag name or commit hash for checkout
GIT_VERSION=v0.5.1

# Package name
NAME=ndndump

# Package version
VERSION=0.5.1

# PPA version
PPA_VERSION=1

include ../packaging.mk
