# URL for git clone
GIT_URL=https://github.com/named-data/ndndump

# Tag name or commit hash for checkout
GIT_VERSION=22f77ef777d7201b3677b04e6b1e0e85c45f0238

# Package name
NAME=ndndump

# Package version
VERSION=0.0.0

# PPA version
PPA_VERSION=1

include ../packaging.mk
