# URL for git clone
GIT_URL=https://github.com/cawka/ChronoSync.git

# Tag name or commit hash for checkout
GIT_VERSION=0.5.0

# Package name
NAME=libchronosync

# Package version
VERSION=0.5.0

# PPA version
PPA_VERSION=2

include ../packaging.mk
