# URL for git clone
GIT_URL=https://github.com/named-data/ChronoSync.git

# Tag name or commit hash for checkout
GIT_VERSION=22eeb2914f66feaa6d8e1c6391dd126bcc37b2ce

# Package name
NAME=libchronosync

# Package version
VERSION=0.5.4-3-g22eeb29

# PPA version
PPA_VERSION=1

include ../packaging.mk
