# URL for git clone
GIT_URL=https://github.com/named-data/ChronoSync.git

# Tag name or commit hash for checkout
GIT_VERSION=5f408ae7f52f2fb792c65db733c80c6d4d5ecf48

# Package name
NAME=libchronosync

# Package version
VERSION=0.5.3-9-g5f408ae

# PPA version
PPA_VERSION=1

include ../packaging.mk
