# URL for git clone
GIT_URL=https://github.com/named-data/repo-ng

# Tag name or commit hash for checkout
GIT_VERSION=595b2bd4020e8c43baf54396eb2c08e1e26fe1ce

# Package name
NAME=repo-ng

# Package version
VERSION=0.0.6

# PPA version
PPA_VERSION=1

include ../packaging.mk
