# URL for git clone
GIT_URL=https://github.com/named-data/repo-ng

# Tag name or commit hash for checkout
GIT_VERSION=959c5b9740cec055def1347be8cb845eec1118af

# Package name
NAME=repo-ng

# Package version
VERSION=0.0.10

# PPA version
PPA_VERSION=2

include ../packaging.mk
