# URL for git clone
GIT_URL=https://github.com/named-data/repo-ng

# Tag name or commit hash for checkout
GIT_VERSION=90d1e88e0d25ea5c19a811091e255d43c6f150ad

# Package name
NAME=repo-ng

# Package version
VERSION=0.0.3

# PPA version
PPA_VERSION=2

include ../packaging.mk
