# URL for git clone
GIT_URL=https://github.com/named-data/ndncert

# Tag name or commit hash for checkout
GIT_VERSION=3e4818421a606c46614e25e66296c6e1a0761a75

# Package name
NAME=ndncert

# Package version
VERSION=0.0.6-1-g3e4818421

# PPA version
PPA_VERSION=1

include ../packaging.mk
