# URL for git clone
GIT_URL=https://github.com/named-data/ndncert

# Tag name or commit hash for checkout
GIT_VERSION=fae76c4dc736b0252e4503ef76c8738afce1d571

# Package name
NAME=ndncert

# Package version
VERSION=0.0.5-1-gfae76c4dc

# PPA version
PPA_VERSION=1

include ../packaging.mk
