# URL for git clone
GIT_URL=https://github.com/named-data/ndncert

# Tag name or commit hash for checkout
GIT_VERSION=857900104088db6ff26e7710da4b4de2762f2361

# Package name
NAME=ndncert

# Package version
VERSION=0.0.4-1-g8579001

# PPA version
PPA_VERSION=1

include ../packaging.mk
