# URL for git clone
GIT_URL=https://github.com/bruinfish/ChronoChat

# Tag name or commit hash for checkout
GIT_VERSION=104a738d6d38a22830e440f97885ac99f76b4044

# Package name
NAME=chronochat

# Package version
VERSION=0.5.0-1

# PPA version
PPA_VERSION=1

include ../packaging.mk
