# URL for git clone
GIT_URL=https://github.com/cawka/ndnmapDataCollector

# Tag name or commit hash for checkout
GIT_VERSION=28df4d5435ee4b94b967133d5f17ecf68167cbe6

# Package name
NAME=ndnmap-data-collector

# Package version
VERSION=0.1.0-5-g28df4d5

# PPA version
PPA_VERSION=1

include ../packaging.mk
