# URL for git clone
GIT_URL=https://github.com/cawka/ndnmapDataCollector

# Tag name or commit hash for checkout
GIT_VERSION=bc631369cce10318269be6d2811038bac1d9f11c

# Package name
NAME=ndnmap-data-collector

# Package version
VERSION=0.1.0-13-gbc63136

# PPA version
PPA_VERSION=1

include ../packaging.mk
