# URL for git clone
GIT_URL=https://github.com/cawka/ndnmapDataCollector

# Tag name or commit hash for checkout
GIT_VERSION=b8e197dbdbc80c6631e31212278f1b70e9165175

# Package name
NAME=ndnmap-data-collector

# Package version
VERSION=0.1.0-18-gb8e197db

# PPA version
PPA_VERSION=1

include ../packaging.mk
